name: Deploy plugins to Flywheel

on:
  workflow_call:
    inputs:
      env_site_slug:
        type: string
        required: true
      env_ssh_host:
        type: string
        required: true
    secrets:
      known_hosts:
        required: true
      flywheel_ssh_user:
        required: true
      flywheel_ssh_key_private:
        required: true

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4
      with:
        fetch-depth: '0'

    - uses: benoitchantre/setup-ssh-authentication-action@1.0.0
      with:
        private-key: ${{ secrets.flywheel_ssh_key_private }}
        private-key-name: deploy-flywheel
        known-hosts: ${{ secrets.known_hosts }}

    - run: |
        rsync -chaviP --stats --no-times --no-perms \
          -e 'ssh -i ~/.ssh/deploy-flywheel' \
          --filter=':- /.gitignore' \
          wp-content/mu-plugins/ "${{ secrets.flywheel_ssh_user }}+${{ inputs.env_site_slug }}@${{ inputs.env_ssh_host }}:/www/wp-content/mu-plugins"
